# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

# file-version: 1.0

name: "Continuous Integration"

on:
  - pull_request
  - push

permissions:
  contents: read
  security-events: read
  issues: read
  pull-requests: read
  checks: read

concurrency:
  group: "${{ github.event_name }}-${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  validate-all:
    name: "Validate Project"

    uses: "mimmi20/ci/.github/workflows/validate-all.yml@8.3"
    with:
      skip-validate-yaml: false
      skip-validate-md: false

  validate-php:
    name: "Validate PHP"

    uses: "mimmi20/ci/.github/workflows/validate-php.yml@8.3"
    with:
      extensions: "ctype, curl, dom, fileinfo, iconv, mbstring, intl, simplexml, tokenizer, xml, xmlwriter, pdo"
      ini-values: "opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0"
      composer-options: "--optimize-autoloader --prefer-dist --prefer-stable -v"
      skip-validate-composer: true
      skip-phplint: false
      skip-check-composer: true
      skip-ec-checker: false
      dependency-analyser-options: "--ignore-unknown-classes"

  install:
    name: "Install Project"

    needs:
      - "validate-all"
      - "validate-php"

    uses: "mimmi20/ci/.github/workflows/install-php.yml@8.3"
    with:
      extensions: "ctype, curl, dom, fileinfo, iconv, mbstring, intl, simplexml, tokenizer, xml, xmlwriter, pdo"
      ini-values: "opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0"
      composer-options: "--optimize-autoloader --prefer-dist --prefer-stable -v"
      skip-librabbitmq-install: true
      skip-libgif-install: true

  analytics:
    name: "Project Analysis"

    permissions:
      security-events: write
      id-token: write
      contents: read
      issues: read
      pull-requests: read
      checks: read

    needs: "install"

    uses: "mimmi20/ci/.github/workflows/analytics-php.yml@8.3"
    with:
      extensions: "ctype, curl, dom, fileinfo, iconv, mbstring, intl, simplexml, tokenizer, xml, xmlwriter, pdo"
      ini-values: "opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0"
      composer-options: "--optimize-autoloader --prefer-dist --prefer-stable -v"
      skip-php-cs-fixer: false
      skip-phpcs: true
      skip-phpstan: false
      skip-rector: false
      use-code-scanning: true
      phpcs-options: ""

  phpcs:
    name: "Check Coding Standards with PHPCS"

    needs: "install"

    runs-on: "${{ matrix.operating-system }}"

    timeout-minutes: 30

    continue-on-error: false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        php-version:
          # Should use the lowest supported version
          - "8.3"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v7"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Install PHP"
        uses: "shivammathur/setup-php@2.37.2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "json, opcache, tokenizer, mbstring"
          ini-values: "opcache.enable=1, opcache.fast_shutdown=0, zend.assertions=1, assert.exception=On, intl.default_locale=de, intl.use_exceptions=1, zend.exception_ignore_args=0"
          coverage: "none"
          tools: "composer:v2, cs2pr"
        env:
          fail-fast: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          phpts: "nts"

      - name: "Update dependencies with composer"
        uses: "ramsey/composer-install@4.0.0"
        with:
          dependency-versions: "lowest"
          composer-options: "--optimize-autoloader --prefer-dist --prefer-stable -v"

      - name: "Run squizlabs/php_codesniffer"
        id: "phpcs"
        run: "vendor/bin/phpcs -wps --colors --standard=src/Mimmi20CodingStandard/ruleset.xml --extensions=php --report-full --report-performance --report-checkstyle=./phpcs-report.xml -v  src test .php-cs-fixer.php rector.php composer-dependency-analyser.php"

      - name: "Show PHPCS results in PR"
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: "cs2pr ./phpcs-report.xml"

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  tests-status:
    name: "Validate & Lint Status"

    runs-on: "ubuntu-latest"

    if: always()

    needs:
      - "analytics"
      - "phpcs"

    steps:
      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
